---
- name: Find all of the configure file inside this directory
  find:
    paths: [/data/mq_admin/rocketmq-all-4.5.1/conf]
    patterns: "logback_*.xml"
  register: logback

- name: Change Log location
  replace:
    path: "{{ item.path }}"
    regexp: "${user.home}"
    replace: "/data/mq_admin"
  with_items: "{{ logback.files }}"
