all:
  hosts:
  children:
    tests:
      hosts:
        aslrxy11:
          ansible_host: 172.17.10.135
          ansible_port: 35192
          ansible_user: pa_eidsvc
    centos:
      hosts:
        centos:
          ansible_host: 172.17.10.135
          ansible_port: 35487
          ansible_user: pa_eidsvc
        orlinux:
          ansible_host: 172.17.10.135
          ansible_port: 35488
          ansible_user: pa_eidsvc
        aulcdm11:
          ansible_host: 172.17.10.135
          ansible_port: 35028
          ansible_user: pa_eidsvc
        aulcdm12:
          ansible_host: 172.17.10.135
          ansible_port: 35029
          ansible_user: pa_eidsvc
        aulcdm13:
          ansible_host: 172.17.10.135
          ansible_port: 35030
          ansible_user: pa_eidsvc
        aulasb11:
          ansible_host: 172.17.10.135
          ansible_port: 35243
          ansible_user: pa_eidsvc
        aplpfw11:
          ansible_host: 172.17.10.135
          ansible_port: 34068
          ansible_user: pa_eidsvc
        aslrxy01:
          ansible_host: 172.17.10.135
          ansible_port: 33033
          ansible_user: pa_eidsvc
        aulsmt01:
          ansible_host: 172.17.10.135
          ansible_port: 34036
          ansible_user: pa_eidsvc
        aslrxy11:
          ansible_host: 172.17.10.135
          ansible_port: 35192
          ansible_user: pa_eidsvc
        aslmsq01:
          ansible_host: 172.17.10.135
          ansible_port: 35161
          ansible_user: pa_eidsvc
        aslmsq11:
          ansible_host: 172.17.10.135
          ansible_port: 35225
          ansible_user: pa_eidsvc
        aulrds15:
          ansible_host: 172.17.10.135
          ansible_port: 35229
          ansible_user: pa_eidsvc
        aulmng11:
          ansible_host: 172.17.10.135
          ansible_port: 35232
          ansible_user: pa_eidsvc
        aslctr01:
          ansible_host: 172.17.10.135
          ansible_port: 35129
          ansible_user: pa_eidsvc
        aslctr02:
          ansible_host: 172.17.10.135
          ansible_port: 35130
          ansible_user: pa_eidsvc
        aulrmq03:
          ansible_host: 172.17.10.135
          ansible_port: 35137
          ansible_user: pa_eidsvc
        aslctr11:
          ansible_host: 172.17.10.135
          ansible_port: 35002
          ansible_user: pa_eidsvc
        aslctr12:
          ansible_host: 172.17.10.135
          ansible_port: 35003
          ansible_user: pa_eidsvc
        aulrmq13:
          ansible_host: 172.17.10.135
          ansible_port: 35010
          ansible_user: pa_eidsvc
        aulfdc11:
          ansible_host: 172.17.10.135
          ansible_port: 35013
          ansible_user: pa_eidsvc
        aulfdc12:
          ansible_host: 172.17.10.135
          ansible_port: 35014
          ansible_user: pa_eidsvc
        aulclb11:
          ansible_host: 172.17.10.135
          ansible_port: 35021
          ansible_user: pa_eidsvc
        aulclb12:
          ansible_host: 172.17.10.135
          ansible_port: 35022
          ansible_user: pa_eidsvc
        aulcmp11:
          ansible_host: 172.17.10.135
          ansible_port: 35023
          ansible_user: pa_eidsvc
        aulcmp12:
          ansible_host: 172.17.10.135
          ansible_port: 35024
          ansible_user: pa_eidsvc
        aulcmp13:
          ansible_host: 172.17.10.135
          ansible_port: 35025
          ansible_user: pa_eidsvc
        aulcmp14:
          ansible_host: 172.17.10.135
          ansible_port: 35026
          ansible_user: pa_eidsvc
        aulcmp15:
          ansible_host: 172.17.10.135
          ansible_port: 35027
          ansible_user: pa_eidsvc
        aulcdr11:
          ansible_host: 172.17.10.135
          ansible_port: 35031
          ansible_user: pa_eidsvc
        aulcdr12:
          ansible_host: 172.17.10.135
          ansible_port: 35032
          ansible_user: pa_eidsvc
        aplftp11:
          ansible_host: 172.17.10.135
          ansible_port: 35528
          ansible_user: pa_eidsvc
        apldns11:
          ansible_host: 172.17.10.135
          ansible_port: 35529
          ansible_user: pa_eidsvc
        aplpxy11:
          ansible_host: 172.17.10.135
          ansible_port: 33094
          ansible_user: pa_eidsvc
        aulrmq04:
          ansible_host: 172.17.10.135
          ansible_port: 35140
          ansible_user: pa_eidsvc
        aulrmq14:
          ansible_host: 172.17.10.135
          ansible_port: 35054
          ansible_user: pa_eidsvc
        aulcdr13:
          ansible_host: 172.17.10.135
          ansible_port: 35034
          ansible_user: pa_eidsvc
        aulslb13:
          ansible_host: 172.17.10.135
          ansible_port: 35050
          ansible_user: pa_eidsvc
        aulslb14:
          ansible_host: 172.17.10.135
          ansible_port: 35051
          ansible_user: pa_eidsvc
        aulmng12:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulrmq01:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulrmq02:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulrmq11:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulrmq12:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulsmm11:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulmvc12:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulmvc13:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulsmd11:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulsmd12:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulsmd13:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulsma11:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulsml11:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aulsmc11:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        apldns12:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aplpxy12:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aplpxy13:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
        aplpxy14:
          ansible_host:
          ansible_port:
          ansible_user: pa_eidsvc
