---
- name: Create broker config file
  template:
    src: templates/config.j2
    dest: /data/mq_admin/rocketmq-all-4.5.1/conf/eidbroker.config
    owner: mq_admin
    group: root
    mode: 0644

- name: Create command file
  template:
    src: templates/runmqbroker.j2
    dest: /usr/local/sbin/runmqbroker
    owner: mq_admin
    group: root
    mode: 0755

- name: Create rocketmq broker service
  template:
    src: templates/broker.j2
    dest: /etc/systemd/system/rmqbroker.service
    owner: mq_admin
    group: root
    mode: 0644

# Use certificates with 2048 bits of key
- name: Creates etc rocketmq directory
  file:
    path: /etc/rocketmq
    state: directory
    mode: "0755"
    owner: mq_admin
    group: mq_admin
- name: Create tls.properties
  template:
    src: templates/tls.properties.j2
    dest: /etc/rocketmq/tls.properties
    owner: mq_admin
    group: root
    mode: "0644"
- name: Copy Certificate files
  copy:
    src: "{{ item }}"
    dest: /etc/rocketmq
    mode: "0644"
    owner: mq_admin
  with_fileglob:
    - files/*

# config java.security file
- name: Disable TLSv1 TLSv1.1 in java.security
  lineinfile:
    path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64/jre/lib/security/java.security
    regexp: "^(.*)jdk.tls.disabledAlgorithms=(.*)$"
    line: 'jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, TLSv1, TLSv1.1, DH keySize < 1024, \\'
    backrefs: yes
    backup: yes

# remove openssl library
- name: Remove openssl library
  file:
    path: /data/mq_admin/rocketmq-all-4.5.1/lib/netty-tcnative-boringssl-static-1.1.33.Fork26.jar
    state: absent
    force: yes

- name: Start broker service
  systemd:
    name: rmqbroker
    daemon_reload: yes
    enabled: yes
    state: restarted
