---
- name: Create command file
  template:
    src: templates/runmqnamesrv.j2
    dest: /usr/local/sbin/runmqnamesrv
    owner: mq_admin
    group: wheel
    mode: 0755

- name: Create rocketmq nameserver service
  template:
    src: templates/nameserver.j2
    dest: /etc/systemd/system/rmqnameserver.service
    owner: mq_admin
    group: wheel
    mode: 0644

- name: Start nameserver service
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable rmqnameserver.service
