---
- name: Create command file
  template:
    src: templates/runmqnamesrv.j2
    dest: /usr/local/sbin/runmqnamesrv
    owner: mq_admin
    group: root
    mode: 0755

- name: Create rocketmq nameserver service
  template:
    src: templates/nameserver.j2
    dest: /etc/systemd/system/rmqnameserver.service
    owner: mq_admin
    group: root
    mode: 0644

- name: Start nameserver service
  systemd:
    name: rmqnameserver
    daemon_reload: yes
    enabled: yes
    state: restarted
